### ISSUE TITLE
Fails to compile in node 4.x

### ISSUE THREAD

**Issue by BryanDonovan** [fuwaneko/node-protobuf#48]
Hi,

`node-protobuf` fails to compile on Mac OS (10.10.5) using Node 4.x.  Here's a gist with the `npm install` output for `node-protobuf` 1.2.7 using Node 4.1.0:

https://gist.github.com/BryanDonovan/0fd216f379b4b857971a

**Comment by fuwaneko** [comment]
Yes, it need to be updated to latest NaN.

**Comment by BryanDonovan** [comment]
That doesn't seem to fix it: https://gist.github.com/BryanDonovan/3a9a4dd627a056bac99a

**Comment by fuwaneko** [comment]
@BryanDonovan obviously, because the code needs to be updated, not just the package.

**Comment by BryanDonovan** [comment]
Thanks.  I thought you just meant that the `nan` package needed to be updated.

**Comment by bgdavidx** [comment]
@BryanDonovan I've updated node-protobuf to work with Node v4.1.1. Hope this helps: https://github.com/fuwaneko/node-protobuf/pull/49

**Comment by jhony-chikens** [comment]
Guys, is it make sense to update major version of the project? Because I've just got the update from 1.2.7 to 1.2.8 and now I can't compile the module with node 0.10.40

**Comment by fuwaneko** [comment]
@jhony-chikens is it impossible to update for 0.12? It's the latest stable in pre-4.0.0 world.

**Comment by jhony-chikens** [comment]
@fuwaneko in my case it kind of complicated mostly because of some other dependencies. But I am just talking about semantic versions and breaking changes. For me it's not such a big problem. It's also possible just to freeze the version on 1.2.7

**Comment by fuwaneko** [comment]
@jhony-chikens in that case, yes, it's better to freeze on 1.2.7. Sorry for non-semantic version update.

**Comment by fuwaneko** [comment]
@jhony-chikens Check 1.2.9, it should work with 0.10 and also includes fix for int64.

**Comment by jhony-chikens** [comment]
@fuwaneko thank you a lot
