### ISSUE TITLE
undefined variable LIBPROTOBUF in binding.gyp

### ISSUE THREAD

**Issue by assslove** [fuwaneko/node-protobuf#66]
when i npm install node-protobuf on windows, the error occur, i had config the LIBPROTOBUF path by your guide, why, could you help me ?

**Comment by fuwaneko** [comment]
I'm afraid I can't help you unless you provide more details about your environment and installation logs.

**Comment by assslove** [comment]
ios: win7 64, i used vc2012 to complise the libprotobuf.lib, the error log as follows:

$ npm install node-protobuf
npm WARN package.json querystring@0.2.0 querystring is also the name of a node core module.
npm WARN package.json crypto@0.0.3 crypto is also the name of a node core module.
npm http GET https://registry.npmjs.org/node-protobuf
npm http 304 https://registry.npmjs.org/node-protobuf
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/bindings
npm http 200 https://registry.npmjs.org/bindings
npm http 200 https://registry.npmjs.org/nan

> node-protobuf@1.2.13 install E:\ss\bleachGMServer\node_modules\node-protobuf
> node-gyp rebuild


E:\ss\bleachGMServer\node_modules\node-protobuf>node "c:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-
gyp: Undefined variable LIBPROTOBUF in binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\ss\bleachGMServer\node_modules\node-protobuf
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! node-protobuf@1.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.2.13 install script.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-protobuf"
npm ERR! cwd E:\ss\bleachGMServer
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     E:\ss\bleachGMServer\npm-debug.log
npm ERR! not ok code 0

**Comment by assslove** [comment]
ios: win7 64, i used vc2012 to complise the libprotobuf.lib, the error log as follows:

$ npm install node-protobuf
npm WARN package.json querystring@0.2.0 querystring is also the name of a node core module.
npm WARN package.json crypto@0.0.3 crypto is also the name of a node core module.
npm http GET https://registry.npmjs.org/node-protobuf
npm http 304 https://registry.npmjs.org/node-protobuf
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/bindings
npm http 200 https://registry.npmjs.org/bindings
npm http 200 https://registry.npmjs.org/nan

> node-protobuf@1.2.13 install E:\ss\bleachGMServer\node_modules\node-protobuf
> node-gyp rebuild


E:\ss\bleachGMServer\node_modules\node-protobuf>node "c:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-
gyp: Undefined variable LIBPROTOBUF in binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\ss\bleachGMServer\node_modules\node-protobuf
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! node-protobuf@1.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.2.13 install script.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-protobuf"
npm ERR! cwd E:\ss\bleachGMServer
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     E:\ss\bleachGMServer\npm-debug.log
npm ERR! not ok code 0

**Comment by fuwaneko** [comment]
Try the latest version.

**Comment by assslove** [comment]
tks

**Comment by fuwaneko** [comment]
Closed due to inactivity.
