### ISSUE TITLE
Errors when installing node-protobuf 

### ISSUE THREAD

**Issue by Omer115** [fuwaneko/node-protobuf#81]
i am very new at this and have no idea what im doing but whenever i try to install the node-protobuf package i keep getting this error a little help would be appreciated.

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Omer\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Omer\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Omer\node_modules\node-protobuf
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Omer\package.json'
npm WARN Omer No description
npm WARN Omer No repository field.
npm WARN Omer No README data
npm WARN Omer No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Omer\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-protobuf"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Omer\npm-debug.log

**Comment by webmakersteve** [comment]
That doesn't seem to give the exact error. Are you installing this from package.json rather than through `npm install node-protobuf`? It looks like you're on Windows, which has pretty complex instructions because you need to get the compiled source lib and headers exported to npm through an environment variable, have you gone through the installation procedure in the README?

**Comment by Omer115** [comment]
i am trying to install this through npm command prompt and as for exporting of the compiled source lib, i have a libprotobuf.lib file but dont know how to export it to npm, thats exactly what im trying to figure out

**Comment by fuwaneko** [comment]
Closing, try v1.4.1 and make sure to use latest npm (npm i -g npm@latest).
