### ISSUE TITLE
Can't find src.obj

### ISSUE THREAD

**Issue by Kidel** [fuwaneko/node-protobuf#83]
While installing node-protobuf

D:\GitHub\POGOserver>npm install node-protobuf

> node-protobuf@1.3.3 install D:\GitHub\POGOserver\node_modules\node-protobuf
> node-gyp rebuild

D:\GitHub\POGOserver\node_modules\node-protobuf>if not defined npm_config_node_gyp (node "C:\Users\tanod\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Compilazione dei progetti nella soluzione uno alla volta. Per abilitare la compilazione parallela, aggiungere l'opzione "/m".
  init.cpp
  native.cpp
  parse.cpp
  serialize.cpp
  win_delay_load_hook.cc
..\src\serialize.cpp(37): warning C4244: 'argomento': conversione da 'double' a 'google::protobuf::int64'. Possibile pe
rdita di dati. [D:\GitHub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\serialize.cpp(50): warning C4244: 'argomento': conversione da 'double' a 'google::protobuf::int64'. Possibile pe
rdita di dati. [D:\GitHub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\serialize.cpp(72): warning C4244: 'argomento': conversione da 'double' a 'google::protobuf::uint64'. Possibile p
erdita di dati. [D:\GitHub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\serialize.cpp(85): warning C4244: 'argomento': conversione da 'double' a 'google::protobuf::uint64'. Possibile p
erdita di dati. [D:\GitHub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\serialize.cpp(96): warning C4244: 'argomento': conversione da 'double' a 'float'. Possibile perdita di dati. [D:
\GitHub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\serialize.cpp(98): warning C4244: 'argomento': conversione da 'double' a 'float'. Possibile perdita di dati. [D:
\GitHub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\native.cpp(39): warning C4267: 'argomento': conversione da 'size_t' a 'int'. Possibile perdita di dati. [D:\GitH
ub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\parse.cpp(144): warning C4267: 'argomento': conversione da 'size_t' a 'uint32_t'. Possibile perdita di dati. [D:
\GitHub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\serialize.cpp(207): warning C4267: '=': conversione da 'size_t' a 'uint32_t'. Possibile perdita di dati. [D:\Git
Hub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\native.cpp(125): warning C4267: 'argomento': conversione da 'size_t' a 'int'. Possibile perdita di dati. [D:\Git
Hub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\native.cpp(130): warning C4267: 'argomento': conversione da 'size_t' a 'int'. Possibile perdita di dati. [D:\Git
Hub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\native.cpp(180): warning C4267: 'argomento': conversione da 'size_t' a 'int'. Possibile perdita di dati. [D:\Git
Hub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\native.cpp(185): warning C4267: 'argomento': conversione da 'size_t' a 'int'. Possibile perdita di dati. [D:\Git
Hub\POGOserver\node_modules\node-protobuf\build\protobuf.vcxproj]
d:\github\pogoserver\node_modules\nan\nan_new.h(208): warning C4244: 'argomento': conversione da 'google::protobuf::int
64' a 'double'. Possibile perdita di dati. (compilazione del file di origine ..\src\parse.cpp) [D:\GitHub\POGOserver\no
de_modules\node-protobuf\build\protobuf.vcxproj]
  ..\src\parse.cpp(60): note: vedere il riferimento all'istanza '<Sconosciuto>' della funzione <Sconosciuto> di cui è i
  n corso la compilazione
d:\github\pogoserver\node_modules\nan\nan_new.h(208): warning C4244: 'argomento': conversione da 'google::protobuf::uin
t64' a 'double'. Possibile perdita di dati. (compilazione del file di origine ..\src\parse.cpp) [D:\GitHub\POGOserver\n
ode_modules\node-protobuf\build\protobuf.vcxproj]
  ..\src\parse.cpp(83): note: vedere il riferimento all'istanza '<Sconosciuto>' della funzione <Sconosciuto> di cui è i
  n corso la compilazione
LINK : warning LNK4044: opzione '/LC:\protobuf' non riconosciuta; verrÓ ignorata [D:\GitHub\POGOserver\node_modules\nod
e-protobuf\build\protobuf.vcxproj]
LINK : fatal error LNK1181: impossibile aprire il file di input 'C:\protobuf-master\src.obj' [D:\GitHub\POGOserver\node
_modules\node-protobuf\build\protobuf.vcxproj]

**Comment by Kidel** [comment]
To clarify, I had the descriptor.h error, then I correctly set up my env variables on Windows, and now this.

**Comment by fuwaneko** [comment]
Last two linker messages suggest that your env variables were set incorrectly.

**Comment by Kidel** [comment]
I have LIBPROTOBUF pointing to protobuf-master (folder from this repo: https://github.com/google/protobuf ) and also protobuf-master/src and protobuf-master/src/google/protobuf/ 

Also there is no src.obj in that repo.

**Comment by Kidel** [comment]
Also why can't I use a precompiled protobuf?

**Comment by Kidel** [comment]
meh, solved by doing it on linux instead of windows... My bad for even trying.

**Comment by fuwaneko** [comment]
Just to clarify: you need to point env variable to the pre-compiled libprotobuf (either do it yourself, or download somewhere, but it has to include headers), not to the cloned source repository.

**Comment by Kidel** [comment]
that's the first thing I've tried, but it didn't work, said a .h file was missing. 
Also there is no precompiled for 64bit windows, or I simply didn't see it. 
No problem however. Everything went fine on linux, I've compiled protobuf there.
